name: Ngrok VPS Setup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-ngrok:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Ngrok
      - name: Install Ngrok
        run: |
          echo "Downloading Ngrok..."
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar -xvf ngrok-v3-stable-linux-amd64.tgz
          chmod +x ngrok
          mv ngrok /usr/local/bin/ngrok
          echo "Verifying Ngrok installation..."
          ngrok --version || { echo "Ngrok installation failed"; exit 1; }

      # Step 3: Debug and Configure Ngrok
      - name: Configure Ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          echo "Checking NGROK_AUTH_TOKEN..."
          if [ -z "$NGROK_AUTH_TOKEN" ]; then
            echo "Error: NGROK_AUTH_TOKEN is empty or not set"
            exit 1
          fi
          echo "NGROK_AUTH_TOKEN is set (masked for security): ${NGROK_AUTH_TOKEN:0:4}****"

          echo "Configuring Ngrok authtoken..."
          ngrok authtoken $NGROK_AUTH_TOKEN || { echo "Failed to set authtoken"; exit 1; }

          echo "Starting Ngrok tunnel for SSH (port 22)..."
          ngrok tcp 22 --log=ngrok.log &

          echo "Waiting for Ngrok to initialize..."
          sleep 20

          echo "Checking Ngrok log file..."
          if [ ! -f ngrok.log ]; then
            echo "Error: ngrok.log not found"
            exit 1
          fi
          cat ngrok.log

          echo "Extracting Ngrok public URL..."
          NGROK_URL=$(grep -o "tcp://[^ ]*" ngrok.log | head -n 1)
          if [ -z "$NGROK_URL" ]; then
            echo "Error: Could not extract Ngrok URL"
            exit 1
          fi

          NGROK_IP=$(echo $NGROK_URL | cut -d'/' -f3 | cut -d':' -f1)
          NGROK_PORT=$(echo $NGROK_URL | cut -d':' -f3)

          echo "VPS_IP_PORT=$NGROK_IP:$NGROK_PORT" >> $GITHUB_ENV
          echo "VPS_USERNAME=${{ secrets.VPS_USERNAME }}" >> $GITHUB_ENV
          echo "VPS_PASSWORD=${{ secrets.VPS_PASSWORD }}" >> $GITHUB_ENV

      # Step 4: Display credentials
      - name: Output VPS Credentials
        run: |
          echo "Connect to VPS using:"
          echo "IP:Port: ${{ env.VPS_IP_PORT }}"
          echo "Username: ${{ env.VPS_USERNAME }}"
          echo "Password: ${{ env.VPS_PASSWORD }}"
