name: Ngrok VPS Setup

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manual trigger bhi rakha hai

jobs:
  setup-ngrok:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Repo checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: SSH into VPS and setup Ngrok
      - name: Setup Ngrok on VPS
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          # Install SSH client
          sudo apt-get update
          sudo apt-get install -y sshpass

          # Install Ngrok
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar -xvf ngrok-v3-stable-linux-amd64.tgz

          # Start Ngrok with authtoken
          ./ngrok authtoken $NGROK_AUTH_TOKEN

          # Start Ngrok tunnel for SSH (port 22)
          ./ngrok tcp 22 --log=stdout > ngrok.log &

          # Wait for Ngrok to initialize
          sleep 10

          # Extract public URL (IP and port)
          NGROK_URL=$(grep -o "tcp://[^ ]*" ngrok.log | head -n 1)
          NGROK_IP=$(echo $NGROK_URL | cut -d'/' -f3 | cut -d':' -f1)
          NGROK_PORT=$(echo $NGROK_URL | cut -d':' -f3)

          # Output credentials
          echo "VPS_IP_PORT=$NGROK_IP:$NGROK_PORT" >> $GITHUB_ENV
          echo "VPS_USERNAME=$VPS_USERNAME" >> $GITHUB_ENV
          echo "VPS_PASSWORD=$VPS_PASSWORD" >> $GITHUB_ENV

      # Step 3: Display credentials
      - name: Output VPS Credentials
        run: |
          echo "Connect to VPS using:"
          echo "IP:Port: ${{ env.VPS_IP_PORT }}"
          echo "Username: ${{ env.VPS_USERNAME }}"
          echo "Password: ${{ env.VPS_PASSWORD }}"
